name: Release Build

on:
  push:
    tags:
      - 'v*' # 触发标签格式为 v开头，如 v1.0.0

# 明确声明工作流所需的权限
permissions:
  contents: write # 允许工作流创建releases和上传构建产物

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的git历史用于版本信息
      
      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      # 构建前端项目
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
      
      # 移动前端构建产物到static目录
      - name: Move Frontend Build
        run: |
          rm -rf src/main/resources/static
          mkdir -p src/main/resources/static
          cp -r frontend/dist/* src/main/resources/static/
      
      # 设置Java环境
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      # 构建后端项目
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      
      # 创建GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            自动构建于 ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
